name: .NET Desktop

on:
  push:
    tags:
      - "*"
  workflow_dispatch: null

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2019  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: MapPortingUtility.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest
        
    - name: Navigate to Workspace
      run: |
        echo $GITHUB_WORKSPACE
        echo ${{ github.workspace }}
        cd $GITHUB_WORKSPACE
      
    - name: Restore Packages
      run: nuget restore $env:Solution_Name
      
    # Build
    - name: Build the application
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Make release zip
      uses: vimtor/action-zip@v1.2
      with:
        files: bin/$Configuration/
        dest: release.zip

    - name: Push automatic release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        prerelease: false
        files: |
          release.zip
